### ISSUE TITLE
Indices break whenever a new paper is added 

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/procbuild#19]
Because of the way indexing is handled, every time there is a new PR all the old indices break. 

This is because the new PR is given the 0 index value (rather than the n index value). A simple fix would be to just organise the building in reverse. 

A real fix would be to index papers by unique keys related to their identity at the time of their creation that can be trusted not to change (paper titles would not work, but user names may not be unique if more than one submission is submitted by the same author).

**Comment by stefanv** [comment]
How about using the GitHub PR number?

**Comment by mpacer** [comment]
We could use that — I tried the reversal approach and it seems like it's not working…

**Comment by mpacer** [comment]
So I think that we should switch it to use a dict based lookup based on the PR number, but that's a bigger change than the reversal for now, so we should make that a new issue if/when we close this one.

**Comment by stefanv** [comment]
Agreed, those IDs are better.
