### ISSUE TITLE
Procbuild website only handles http

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/procbuild#26]
I tend to default to https for everything, it’d be nice if we could get an ssl certificate for the site so we could have https access.

**Comment by mpacer** [comment]
Ugh probably we won’t want to do that: it requires a paid extension https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by stefanv** [comment]
You can add SSL through CloudFlare or similar services, but here it does not make much sense since we're not passing any hidden information around.

**Comment by cbcunc** [comment]
https://procbuild.scipy.org was accomplished with an nginx proxy.
