### ISSUE TITLE
Procbuild is using vanderwalt example pdf rather than successfully PR papers

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/procbuild#3]
So... in the buildbot, we have a handful of papers which should successfully build (see Dask), but the procbuild system seems to be building only the example vanderwalt file. Currently we exclude '00_vanderwalt', 'vanderwalt', and 'jane_doe'... however the pdf that is being built is the vanderwalt paper  rather than the (for example) Dask paper.

**Comment by katyhuff** [comment]
any ideas on this @stefanv ? I'm a little stumped... I think it might be solved if these folks updated their branches to include the recent changes to 00_vanderwalt, but I'm really not sure... it should be excluding that folder... confusing.

**Comment by stefanv** [comment]
I just browsed there and it looks fine to me.  Perhaps browser-side caching?

**Comment by katyhuff** [comment]
Oh man, good call. That means my "exclude 00_vanderwalt" additon worked. I'll push that fix... now that I know it helped.

**Comment by katyhuff** [comment]
Added this to fix failure to exclude: dcf36cece43f15df1a96f1c9b8b39fc14f78ec65 .

**Comment by stefanv** [comment]
Also feel free to permanently rename the 00_vanderwalt paper to doe_jane

**Comment by katyhuff** [comment]
no need, the jane_doe bit was just from me testing the build server a while
back. I like vanderwalt. :D

On Mon, Jun 15, 2015 at 11:08 AM, Stefan van der Walt <
notifications@github.com> wrote:

> Also feel free to permanently rename the 00_vanderwalt paper to doe_jane
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/procbuild/issues/3#issuecomment-112157031>
> .
>



-- 
http://katyhuff.github.com

**Comment by stefanv** [comment]
Vanderwalt appreciates that! :)
