### ISSUE TITLE
Dockerfile Fixes

### ISSUE THREAD

**Issue by cbcunc** [scipy-conference/procbuild#39]
Need the following fixes to the Dockerfile:

1. Should be able to set UID and GID of procbuild user in order to persist paper cache.
1. Ubuntu:17.10 no longer available on DockerHub. Switch to latest.
1. Installing package on Ubuntu:latest pulls in tzdata dependency which interactively asks for timezone, stopping docker build. Needs `ENV DEBIAN_FRONTEND=noninteractive`.
1. Ubuntu:latest requires explicit installation of pyhon3-venv.

**Comment by deniederhut** [comment]
Closed in e266330ce723b2ff3d3df638d035ed3e773994ea
